include mk.config

OBJS := $(OBJDIR)/alloc.o $(OBJDIR)/grep.o $(OBJDIR)/grid.o

LIB_GREP := $(OBJDIR)/libgrep.a
LIB_COMMON := libcommon/libcommon.a
LIB_UXRE := libuxre/libuxre.a

all: egrep fgrep grep grep_sus grep_su3

egrep: $(OBJS) $(LIB_GREP) $(LIB_COMMON) $(LIB_UXRE) $(OBJDIR)/egrep_main.o $(OBJDIR)/plist.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

fgrep: $(OBJS) $(LIB_GREP) $(LIB_COMMON) $(LIB_UXRE)  $(OBJDIR)/fgrep_main.o $(OBJDIR)/plist.o $(OBJDIR)/ac.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep: $(OBJS)  $(LIB_GREP) $(LIB_COMMON) $(LIB_UXRE) $(OBJDIR)/grep_main.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep_sus: $(OBJS) $(LIB_GREP)  $(LIB_COMMON) $(LIB_UXRE) $(OBJDIR)/plist.o $(OBJDIR)/rcomp.o $(OBJDIR)/sus.o $(OBJDIR)/ac.o
	$(LD) $(LDFLAGS) $^ $(LUXRE) $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep_su3: $(OBJS) $(LIB_GREP) $(LIB_COMMON) $(LIB_UXRE)  $(OBJDIR)/plist.o $(OBJDIR)/rcomp.o $(OBJDIR)/su3.o $(OBJDIR)/ac.o
	$(LD) $(LDFLAGS) $^ $(LUXRE) $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

$(OBJDIR)/%.o: %.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c $< -o $@

$(OBJDIR)/sus.o: sus.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -DSUS -c $< -o $@

$(OBJDIR)/su3.o: sus.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -DSU3 -c $< -o $@

egrep_main.c: egrep.y
	yacc egrep.y
	mv -f y.tab.c egrep_main.c

$(OBJDIR):
	@mkdir -p $@

$(LIB_GREP): $(OBJDIR)/grep.o
	$(AR) -rv $@ $<
	$(RANLIB) $@

$(LIB_COMMON):
	cd libcommon && $(MAKE) -f Makefile.mk

$(LIB_UXRE):
	cd libuxre && $(MAKE) -f Makefile.mk

test: grep
	@echo "Running smoke tests.."
	cd .. && G=./after/grep SYS_GREP=/bin/grep bash smoke-test.sh

install: all
	$(UCBINST) -c egrep $(ROOT)$(SV3BIN)/egrep
	$(STRIP) $(ROOT)$(SV3BIN)/egrep
	$(UCBINST) -c fgrep $(ROOT)$(SV3BIN)/fgrep
	$(STRIP) $(ROOT)$(SV3BIN)/fgrep
	$(UCBINST) -c grep $(ROOT)$(SV3BIN)/grep
	$(STRIP) $(ROOT)$(SV3BIN)/grep
	$(UCBINST) -c grep_sus $(ROOT)$(SUSBIN)/grep
	$(STRIP) $(ROOT)$(SUSBIN)/grep
	rm -f $(ROOT)$(SUSBIN)/egrep $(ROOT)$(SUSBIN)/fgrep
	$(LNS) grep $(ROOT)$(SUSBIN)/egrep
	$(LNS) grep $(ROOT)$(SUSBIN)/fgrep
	$(UCBINST) -c grep_su3 $(ROOT)$(SU3BIN)/grep
	$(STRIP) $(ROOT)$(SU3BIN)/grep
	rm -f $(ROOT)$(SU3BIN)/egrep $(ROOT)$(SU3BIN)/fgrep
	$(LNS) grep $(ROOT)$(SU3BIN)/egrep
	$(LNS) grep $(ROOT)$(SU3BIN)/fgrep
	$(MANINST) -c -m 644 egrep.1 $(ROOT)$(MANDIR)/man1/egrep.1
	$(MANINST) -c -m 644 fgrep.1 $(ROOT)$(MANDIR)/man1/fgrep.1
	$(MANINST) -c -m 644 grep.1 $(ROOT)$(MANDIR)/man1/grep.1

clean:
	cd libcommon && $(MAKE) -f Makefile.mk clean
	cd libuxre && $(MAKE) -f Makefile.mk clean
	rm -rf $(OBJDIR) egrep fgrep grep grep_sus grep_su3 egrep.c

config.h:
	-echo '/*	Auto-generated by make. Do not edit!	*/' >config.h
	-echo '#include	<wchar.h>' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#include	<wchar.h>' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c
	-echo '#include	<wctype.h>' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#include	<wctype.h>' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c
	-echo 'long long foo;' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#define	LONGLONG' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c

$(OBJDIR)/grep.o: public.h config.h alloc.h
$(OBJDIR)/plist.o: public.h config.h alloc.h
$(OBJDIR)/svid3.o: public.h config.h
$(OBJDIR)/sus.o: public.h config.h alloc.h
$(OBJDIR)/su3.o: public.h config.h alloc.h
$(OBJDIR)/ac.o: alloc.h grep.h
$(OBJDIR)/rcomp.o: public.h config.h alloc.h
