include mk.config

OBJS := $(OBJDIR)/alloc.o $(OBJDIR)/grep.o $(OBJDIR)/grid.o

all: egrep fgrep grep grep_sus grep_su3

egrep: $(OBJS) $(OBJDIR)/egrep.o $(OBJDIR)/plist.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

fgrep: $(OBJS) $(OBJDIR)/fgrep.o $(OBJDIR)/plist.o $(OBJDIR)/ac.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep: $(OBJS) $(OBJDIR)/ggrep.o $(OBJDIR)/svid3.o
	$(LD) $(LDFLAGS) $^ $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep_sus: $(OBJS) $(OBJDIR)/plist.o $(OBJDIR)/rcomp.o $(OBJDIR)/sus.o $(OBJDIR)/ac.o
	$(LD) $(LDFLAGS) $^ $(LUXRE) $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

grep_su3: $(OBJS) $(OBJDIR)/plist.o $(OBJDIR)/rcomp.o $(OBJDIR)/su3.o $(OBJDIR)/ac.o
	$(LD) $(LDFLAGS) $^ $(LUXRE) $(LCOMMON) $(LWCHAR) $(LIBS) -o $@

$(OBJDIR)/%.o: %.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c $< -o $@

$(OBJDIR)/sus.o: sus.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -DSUS -c $< -o $@

$(OBJDIR)/su3.o: sus.c | $(OBJDIR)
	$(CC) $(CFLAGSS) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -DSU3 -c $< -o $@

$(OBJDIR):
	@mkdir -p $@

install: all
	$(UCBINST) -c egrep $(ROOT)$(SV3BIN)/egrep
	$(STRIP) $(ROOT)$(SV3BIN)/egrep
	$(UCBINST) -c fgrep $(ROOT)$(SV3BIN)/fgrep
	$(STRIP) $(ROOT)$(SV3BIN)/fgrep
	$(UCBINST) -c grep $(ROOT)$(SV3BIN)/grep
	$(STRIP) $(ROOT)$(SV3BIN)/grep
	$(UCBINST) -c grep_sus $(ROOT)$(SUSBIN)/grep
	$(STRIP) $(ROOT)$(SUSBIN)/grep
	rm -f $(ROOT)$(SUSBIN)/egrep $(ROOT)$(SUSBIN)/fgrep
	$(LNS) grep $(ROOT)$(SUSBIN)/egrep
	$(LNS) grep $(ROOT)$(SUSBIN)/fgrep
	$(UCBINST) -c grep_su3 $(ROOT)$(SU3BIN)/grep
	$(STRIP) $(ROOT)$(SU3BIN)/grep
	rm -f $(ROOT)$(SU3BIN)/egrep $(ROOT)$(SU3BIN)/fgrep
	$(LNS) grep $(ROOT)$(SU3BIN)/egrep
	$(LNS) grep $(ROOT)$(SU3BIN)/fgrep
	$(MANINST) -c -m 644 egrep.1 $(ROOT)$(MANDIR)/man1/egrep.1
	$(MANINST) -c -m 644 fgrep.1 $(ROOT)$(MANDIR)/man1/fgrep.1
	$(MANINST) -c -m 644 grep.1 $(ROOT)$(MANDIR)/man1/grep.1

clean:
	rm -rf $(OBJDIR) egrep fgrep grep grep_sus grep_su3

config.h:
	-echo '/*	Auto-generated by make. Do not edit!	*/' >config.h
	-echo '#include	<wchar.h>' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#include	<wchar.h>' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c
	-echo '#include	<wctype.h>' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#include	<wctype.h>' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c
	-echo 'long long foo;' >___build$$$$.c ; \
	$(CC) $(CFLAGS2) $(CPPFLAGS) $(IWCHAR) $(ICOMMON) $(IUXRE) $(LARGEF) -c ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$.o ; \
	then	echo '#define	LONGLONG' >>config.h ; \
	fi ; \
	rm -f ___build$$$$.o ___build$$$$.c

$(OBJDIR)/grep.o: grep.h config.h alloc.h
$(OBJDIR)/egrep.o: grep.h config.h alloc.h
$(OBJDIR)/fgrep.o: grep.h config.h
$(OBJDIR)/ggrep.o: grep.h config.h
$(OBJDIR)/plist.o: grep.h config.h alloc.h
$(OBJDIR)/svid3.o: grep.h config.h
$(OBJDIR)/sus.o: grep.h config.h alloc.h
$(OBJDIR)/su3.o: grep.h config.h alloc.h
$(OBJDIR)/ac.o: alloc.h grep.h
$(OBJDIR)/rcomp.o: grep.h config.h alloc.h
